---
title: "Collections Monthly Report for July 2019"
author: "Snap Analytics Team"
date: "8/1/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
```

```{r}
# Automate later (Getting the data)
library(dplyr)

get_data <- function(filename='predictions.csv', mon=7, yr=2019){
  d <- read.csv(filename, stringsAsFactors = FALSE)
  colnames(d)[1] <- 'date'
  d$date <- as.Date(d$date, format='%m/%d/%Y')
  d$weekday = substr(strftime(d$date,'%A'),1,3)
  d <- d[d$weekday != 'Sun',]
  d <- d[d$date != '2019-07-04',] # Remove holidays
  d[is.na(d)] <- 0
  d[,c(1,6,2:5)]
}

# Split into 2 separate datafiles
all.dat <- get_data()
dat.sday <- get_data()[, c(1:2, which(grepl('sameday', colnames(all.dat))))]
dat.total <- get_data()[, c(1:2, which(grepl('total', colnames(all.dat))))]

# Function that adds other metrics. Will find actual and targeted columns (only 1 of each)
add.metrics <- function(df){
  act.col <- which(grepl('actual', tolower(colnames(df))))
  trg.col <- which(grepl('target', tolower(colnames(df))))
  if((length(act.col) != 1) | (length(trg.col) != 1)) stop('incorrect format')
  
  df$Prediction_Error <- df[,act.col] - df[,trg.col]
  df$Cum_Collected <- cumsum(df[, act.col])
  df$Cum_Targeted <- cumsum(df[, trg.col])
  df$Targeted_Dollars_Difference <- df$Cum_Collected - df$Cum_Targeted
  colnames(df)[c(act.col, trg.col)] <- c('dollars_collected', 'dollars_targeted')
  df
}

tab_sday <- add.metrics(dat.sday)
tab_tot <- add.metrics(dat.total)
```

```{r}
library(DT)
make.table <- function(df_tab){
  datatable(
    df_tab %>%
      select('Date'='date'
             ,'Weekday' = 'weekday'
             ,'Dollars Targeted'='dollars_targeted'
             ,'Dollars Collected'='dollars_collected'
             ,'Prediction Error'='Prediction_Error'
             ,'Targeted Dollars Difference'='Targeted_Dollars_Difference')
    ,rownames=FALSE
    ,filter = "top"
    ,extensions = c("FixedColumns","Buttons")
    , options = list(
      dom = 'Bfrtip'
      , buttons = c('colvis', 'csv', 'excel', 'pdf')
      , pageLength = -1
      , searchHighlight = TRUE
      , height="67%"
      , fixedColumns = list(leftColumns = 1)
      , scrollX =TRUE
    )
  ) %>% formatCurrency(c('Dollars Targeted', 'Dollars Collected', 'Prediction Error'
                         , 'Targeted Dollars Difference')) %>%
    formatStyle(1:7, fontWeight = 'bold') %>%
    formatStyle(
      c('Prediction Error','Targeted Dollars Difference'),
      color = styleInterval(0, c('red', 'green'))
  )
}
```




```{r}
library(highcharter)

hc_tooltip_goals <- function(hc){
  hc %>%
    hc_tooltip(shared=TRUE, useHTML=TRUE,
               headerFormat='<small>{point.key}</small><table>',
               pointFormat=paste0('<tr><td style="color: {series.color}"><span style="color:{point.color}">\u25CF</span>{series.name}: </td>',
                                  '<td style="text-align: right"><b>{point.y}</b></td></tr>'),
               footerFormat= '</table>',
               valueDecimals=2, valuePrefix='$')
}

make.graph <- function(df_tab, title='Daily View'){
  highchart() %>%
    hc_add_series_times_values(df_tab$date, df_tab$dollars_collected,
                               name = "Collected Dollars", lineWidth = 4, color = "#1E2C5A") %>%
    hc_add_series_times_values(df_tab$date, df_tab$dollars_targeted,
                               name= "Targeted Dollars", lineWidth = 4, color = "#8ec640") %>%
    hc_tooltip_goals() %>% 
    hc_title(text=title)
  
  
}

make.cum.graph <- function(df_tab, title='Overall View'){
  highchart() %>%     
    hc_add_series_times_values(df_tab$date, df_tab$Cum_Collected, 
                                 name = "Collected Dollars", lineWidth = 2.5, color = "#1E2C5A") %>%
    hc_add_series_times_values(df_tab$date, df_tab$Cum_Targeted, 
                                 name= "Targeted Dollars", lineWidth = 2.5, color = "#8ec640") %>%
    hc_tooltip_goals() %>% 
    hc_title(text=title)
  
}
```


# Arrangement Dollars
```{r}
make.table(tab_tot)
make.graph(tab_tot)
make.cum.graph(tab_tot)
```



# Same-Day Dollars
```{r}
make.table(tab_sday)
make.graph(tab_sday)
make.cum.graph(tab_sday)
```

<!--  ```{r} -->
<!--  mean(abs(tab_sday$Prediction_Error)) # MAE 9282.4 -->
<!--  ``` -->

